### ISSUE TITLE
Feature: User can search the MAL catalog

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#1]
## ⚙️ Feature

User can search the MAL catalog

## 📐 Functionality

Responsive form that allows users to search for anime

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97260501/155811305-1b154913-b72a-4b9e-a209-1f0f8302f834.png)
![image](https://user-images.githubusercontent.com/97260501/155811327-7f34633c-08b0-4bc3-b8f5-ecac0600fae6.png)

## ✅ Task List

- [x] Create html layout to match the wireframes
- [x] Make HTTPie request to get data from MAL
- [x] Add listeners for search bar
- [x] Create array of objects to represent search results
- [x] Create unordered list of elements to populate list
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
- [x] Remove console.logs
