### ISSUE TITLE
Feature:  Search Tab

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#15]
## ⚙️ Feature

User can access search from tab

## ✅ Task List

- [x] Search brings up detail modal
- [x] Modal has button to add to lists
- [x] Modal chooses list based on user choice
- [x] Remove Add buttons
