### ISSUE TITLE
Feature: Move entry to list button

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#16]
## ⚙️ Feature

Entry list has button that can move an entry from one list to the list to the left of it

## ✅ Task List

- [ ] Create left button element
- [ ] Button changes behavior based upon what list is open
- [ ] List entry is removed from current list and pushed to new one
- [ ] Location is logged
- [ ] Create undo entry element
- [ ] If user clicks on '.entry-item' > check if '#undo-entry'
- [ ] Remove entry and logged location when switch views
