### ISSUE TITLE
Feature: CSS Polish

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#17]
## ⚙️ Feature

Add css cool stuff

## ✅ Task List

- [ ] '.entry-list' changes color on hover
- [ ] Click animations on '.entry-list'
- [ ] Animation for moving entries from different lists
- [ ] Bar that moves between each tab
- [ ] 'ul' moves right and left when tab switched
- [ ] Animated search icon
- [ ] Background to detail views
