### ISSUE TITLE
Feature: User can add search result to their watch list

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#2]
## ⚙️ Feature

User can add search result to their watch list

## 📐 Plan

Add search result to watch list and populate watch list

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97260501/155812779-98d3453c-c07f-40c6-9dc7-8eadb45b93c4.png)
![image](https://user-images.githubusercontent.com/97260501/155812848-455c2aad-24cd-4989-ab8b-c78f4891fd0d.png)

## ✅ Task List

- [x] Create HTML layout that matches wireframes
- [x] Create array of objects to represent watch list
- [x] Create unordered list of elements to populate list
- [x] Create add button that goes to search
- [x] Create button that changes episode count
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
- [x] Remove console.logs
