### ISSUE TITLE
Feature: User can add search result to their queue list

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#3]
## ⚙️ Feature

User can add search result to their queue list

## 📐 Plan

Add search result to watch list and populate watch list

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97260501/155813382-da712978-cd91-472d-a82c-c34d8090870a.png)
![image](https://user-images.githubusercontent.com/97260501/155813419-4fe5c5d8-dbea-4d82-9bd7-3a50848e83b4.png)

## ✅ Task List

- [x] Create HTML layout that matches wireframes
- [x] Create array of objects to represent watch list
- [x] Create ordered list of elements to populate list
- [x] Create add button that goes to search
- [x] Make navigation bar in header
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
- [x] Remove console.logs
