### ISSUE TITLE
Feature: User can increment episode count on watch list

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#4]
## ⚙️ Feature

User can increment episode count on watch list

## 📐 Plan

Create buttons on each element that will increment episode count

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97260501/155813652-43a442c9-ab4f-45b2-b653-c7f10f30dc9b.png)
![image](https://user-images.githubusercontent.com/97260501/155813628-14e5cd2f-cfed-40c7-b755-8cfa8a204e6f.png)

## ✅ Task List

- [ ] Add listener to button element
- [ ] Create function that increments episode count in watch list
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary
- [ ] Test all functionality again in a private browsing session
- [ ] Fix all errors
- [ ] Remove console.logs
