### ISSUE TITLE
Feature: User can view ratings list with summaries

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#5]
## ⚙️ Feature

User can view ratings list with summaries

## 📐 Plan

Populate ratings list

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97260501/155813928-c1a4a32a-553e-480a-a2db-585920fe8e1e.png)
![image](https://user-images.githubusercontent.com/97260501/155813940-fd0591ab-2656-4ddf-858d-5acac071e175.png)

## ✅ Task List

- [x] Create HTML layout that matches wireframes
- [x] Create array of objects to represent ratings list
- [x] Create unordered list of elements to populate list
- [x] Create add button that goes to search
- [x] Create function that organizes entries by score
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
- [x] Remove console.logs
