### ISSUE TITLE
Feature: User can add a rating with their review

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#6]
## ⚙️ Feature

User can add a rating with their review

## 📐 Plan

Create form that will add new object to rating list

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97260501/155814208-b978b291-70e9-445a-a7c5-18e2bd9cfe01.png)
![image](https://user-images.githubusercontent.com/97260501/155814235-a5f5d934-491b-4c9c-96ee-8f3e575c6d3b.png)

## ✅ Task List

- [x] Create HTML layout that matches wireframes
- [x] Create form with thoughts, review, and score as inputs
- [x] Create a submit button that will add the rating to rating list and return to ratings page
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
- [x] Remove console.logs
