### ISSUE TITLE
Feature: User can see their full review

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#7]
## ⚙️ Feature

User can see their full review

## 📐 Plan

Create page that shows their whole review

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97260501/155814476-64763961-d547-49dd-9214-36439cf80843.png)
![image](https://user-images.githubusercontent.com/97260501/155814493-a5e7b2bb-bbf3-4a74-8e0e-71127da5b46d.png)

## ✅ Task List

- [x] Create HTML layout that matches wireframes
- [x] Add edit button that will return to create rating screen
- [x] Prepopulate with object details
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
- [x] Remove console.logs
