### ISSUE TITLE
Feature: User can search for anime in their watch and queue list

### ISSUE THREAD

**Issue by Justin-Arakaki** [Justin-Arakaki/ajax-project#8]
## ⚙️ Feature

User can search for anime in their watch and queue list

## 📐 Plan

Form that searches based upon genre and vibe

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97260501/155814756-78fc016f-3312-4496-8bff-562f66642416.png)
![image](https://user-images.githubusercontent.com/97260501/155814768-9b271bd6-87d1-47b3-9c1e-a121ae848130.png)

## ✅ Task List

- [ ] Create form with vibe and genre search criteria
- [ ] Create function that searches watching and queue list
- [ ] Populate recommendations with elements that represent results
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary
- [ ] Test all functionality again in a private browsing session
- [ ] Fix all errors
- [ ] Remove console.logs
